name: Continuous integration/deployment
on: [push]
jobs:

  commitlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2

  site:
    needs: commitlint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./packages/site/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Checkout prevbox-site
        uses: actions/checkout@v1

      - name: Set up node 12.22.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.1

      - name: Install Site dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build Production
        run: npm run build

      - name: Set up AWS CLI
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: drivebox-site
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
          SOURCE_DIR: './out'

      # - name: CloudFront invalidation (Production) - fieldcontrol.com.br
      #   if: github.ref == 'refs/heads/master'
      #   run: node ./bin/create_cloudfront_invalidation.js
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     CLOUDFRONT_DISTRIBUTION_ID: E3C4B1KX1BJOU1